### PR TITLE
Use versionless GRASS GIS (8) instead of hardcoded grass7x

### PR DESCRIPTION
**Pull request by neteler**
- also change to GRASS GIS 8 addons

Related to https://github.com/mundialis/actinia_core/issues/331

### CODE REVIEW

**Review by anikaweinmann — COMMENTED** [review]
Please also customize in docker:
- https://github.com/mundialis/actinia-stac-plugin/blob/main/docker/actinia-stac-tests/actinia-stac-test.cfg#L6

And check if the tests work again.

**Comment by neteler** [comment]
> Please also customize in docker:
> 
>     * https://github.com/mundialis/actinia-stac-plugin/blob/main/docker/actinia-stac-tests/actinia-stac-test.cfg#L6

It was locally already done but I fail to bypass the `.gitignore` barrier. Not even `git add -f ...` works... Any trick here?

**Comment by neteler** [comment]
That should already be done but the test fails (for other reasons?).

**Comment by anikaweinmann** [comment]
@neteler the tests probably fail because an old actinia-core image is still used. In the other plugins I have partially used simply `latest`: https://github.com/mundialis/actinia-stac-plugin/blob/main/docker/actinia-stac-tests/Dockerfile#L1

**Comment by neteler** [comment]
Still no success, even with the latest actinia docker image:

It fails at "Test if app responds":
https://github.com/mundialis/actinia-stac-plugin/blob/719648c0549deb85410522d2a7540561fdfc6b0c/tests/test_stac.py#L32


```
#15 22.74 ============================= test session starts ==============================
#15 22.74 platform linux -- Python 3.9.7, pytest-7.1.2, pluggy-0.13.1 -- /usr/bin/python3
#15 22.74 cachedir: .pytest_cache
#15 22.74 rootdir: /src/actinia-stac-plugin, configfile: setup.cfg
#15 22.74 plugins: cov-3.0.0
#15 22.74 collecting ... collected 15 items
#15 26.88 
#15 26.88 tests/test_stac.py::StacEndpointTest::test_a_app_instances FAILED        [  6%]
#15 27.65 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> traceback >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#15 27.65 E   assert 404 == 200
#15 27.65      +  where 404 = <Response streamed [404 NOT FOUND]>.status_code
#15 27.65 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> entering PDB >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#15 27.65 
#15 27.65 >>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>
#15 27.65 > /src/actinia-stac-plugin/tests/test_stac.py(37)test_a_app_instances()
#15 27.65 -> assert resp.status_code == 200
#15 27.65 (Pdb) 
#15 28.26 
```

**Comment by mmacata** [comment]
I will merge anyway, the changes don't seem related to the failing tests.

**Pull request merged**
